package com.pomplarg.spe95.utils

class Constants {
    companion object {
        const val FIRESTORE_CYNO_DOCUMENT = "cyno"
        const val FIRESTORE_SD_DOCUMENT = "sd"
        const val FIRESTORE_RA_DOCUMENT = "ra"

        const val TYPE_OPERATION_INTERVENTION = "Intervention"
        const val TYPE_OPERATION_TRAINING = "Entrainement"
        const val TYPE_OPERATION_FORMATION = "Formation"
        const val TYPE_OPERATION_INFORMATION = "Information"

        const val SHARED_PREF_FRAGMENT_KEY = "SHARED_PREF_FRAGMENT_KEY"

        const val ADD_OPERATION_DATE_FORMAT_DISPLAY = "dd/MM/yyyy"
        const val ADD_OPERATION_TIME_FORMAT_DISPLAY = "HH:mm"

        const val CYNO_DOG_IPSO = "Ipso"
        const val CYNO_DOG_NANO = "Nano"
        const val CYNO_DOG_NERONE = "Nerone"
        const val CYNO_DOG_PRIAXE = "Priaxe"

        const val SD_LSPCC = "LSPCC / Main courante"
        const val SD_ECH_COULISSE = "Echelle à coulisse"
        const val SD_TELESTEP = "Telestep"
        const val SD_GR_ELEC_FIXE = "Fixe"
        const val SD_GR_ELEC_22001 = "22001"
        const val SD_GR_ELEC_22002 = "22002"
        const val SD_GR_ELEC_30001 = "30001"
        const val SD_GR_ELEC_30002 = "30002"
        const val SD_ECL_SOLARIS = "Solaris"
        const val SD_ECL_NEON = "Néon"
        const val SD_ECL_LUMAPHORE = "Lumaphore"
        const val SD_ECL_BABY = "Baby"
        const val SD_PERC_GRP_HYDRAU = "Groupe hydraulique"
        const val SD_PERC_TRONC_DISQUE = "Tronçonneuse à disque"
        const val SD_PERC_TRONC_CHAINE = "Tronçonneuse à chaine"
        const val SD_PERC_CHAINE_DIAM = "Chaine diamant"
        const val SD_PERC_CHAINE_CARB = "Chaine carbure"
        const val SD_PERC_PERFORATEUR = "Perforateur"
        const val SD_PERC_OXYDECOUPEUR = "Oxydécoupeur"
        const val SD_FORCE_TIRFOR = "Tirfor"
        const val SD_FORCE_SANG_TEXT = "Sangle textile"
        const val SD_FORCE_COUSS_LEVAGE = "Coussin levage"
        const val SD_ETAIEMENT_PNEUM = "Etai pneumatique"
        const val SD_ETAIEMENT_METAL_PETIT = "Etai métallique petit"
        const val SD_ETAIEMENT_METAL_MOYEN = "Etai métallique moyen"
        const val SD_ETAIEMENT_METAL_GRAND = "Etai métallique grand"
        const val SD_ETAIEMENT_BOIS_GOUSSET = "Bois gousset"
        const val SD_ETAIEMENT_BOIS_VOLIGE = "Bois volige"
        const val SD_ETAIEMENT_BOIS_CHEVRON = "Bois chevron"
        const val SD_ETAIEMENT_BOIS_BASTAING = "Bois bastaing"
        const val SD_EXPLO_ASB8 = "ASB8"
        const val SD_EXPLO_CAMERA = "Caméra"
        const val SD_PETIT_MAT_VISSEUSE = "Visseuse"
        const val SD_PETIT_MAT_VIS = "Vis"
        const val SD_PETIT_MAT_CORDAGE = "Cordage"
        const val SD_PETIT_MAT_SERVANTE = "Servante"
        const val SD_PETIT_MAT_CARBURANT_SP95 = "Carburant SP95"
        const val SD_PETIT_MAT_CARBURANT_MARLINE = "Carburant marline"
        const val SD_PETIT_MAT_CARBURANT_MELANGE = "Carburant mélange 4%"
        const val SD_PETIT_MAT_CARBURANT_HUILE_CHAINE = "Carburant huile de chaine"

        const val RA_ANIMAL_ESPECE_CAT = "Espece Chat"
        const val RA_ANIMAL_ESPECE_DOG = "Espece Chien"
        const val RA_ANIMAL_ESPECE_OTHER = "Espece "
        const val RA_ANIMAL_TYPE_DOMESTIQUE = "Type Domestique"
        const val RA_ANIMAL_TYPE_SAUVAGE = "Type Sauvage"
        const val RA_ANIMAL_TYPE_ELEVAGE = "Type Elevage"
        const val RA_ANIMAL_TYPE_AUTOCHTONE = "Type Autochtone"
        const val RA_ANIMAL_PRISE_CHARGE_COOPERATIF = "Prise en charge Cooperatif"
        const val RA_ANIMAL_PRISE_CHARGE_MENACANT = "Prise en charge Menaçant"
        const val RA_ANIMAL_PRISE_CHARGE_BLESSE = "Prise en charge Blessé"
        const val RA_ANIMAL_PRISE_CHARGE_MORDEUR = "Prise en charge Mordeur"
        const val RA_ANIMAL_PRISE_CHARGE_MORT = "Prise en charge Mort"
        const val RA_ANIMAL_PRISE_CHARGE_ANESTHESIE = "Prise en charge Anesthesié"
        const val RA_ANIMAL_DESTINATION_CENTRE_REGROUPEMENT = "Destination Centre de regroupement"
        const val RA_ANIMAL_DESTINATION_CEDAF = "Destination CEDAF"
        const val RA_ANIMAL_DESTINATION_PROPRIETAIRE = "Destination Propriétaire"
        const val RA_ANIMAL_DESTINATION_CLINIQUE_VETERINAIRE = "Destination Clinique vétérinaire de l'isle Adam"
        const val RA_ANIMAL_DESTINATION_OTHER = "Destination "
        const val RA_ANIMAL_TRANSPORT_VIRA = "Transport VIRA"
        const val RA_ANIMAL_TRANSPORT_VTU = "Transport VTU"
        const val RA_ANIMAL_TRANSPORT_OTHER = "Transport "
        const val RA_ANIMAL_ENGINS_SUR_LIEUX_VTU = "Engins sur les lieux VTU"
        const val RA_ANIMAL_ENGINS_SUR_LIEUX_FPT = "Engins sur les lieux FPT"
        const val RA_ANIMAL_ENGINS_SUR_LIEUX_VSR = "Engins sur les lieux VSR"
        const val RA_ANIMAL_ENGINS_SUR_LIEUX_MOYEN_AERIEN = "Engins sur les lieux Moyen aérien"
        const val RA_ANIMAL_ENGINS_SUR_LIEUX_VSAV = "Engins sur les lieux VSAV"
        const val RA_ANIMAL_ENGINS_SUR_LIEUX_VSSO = "Engins sur les lieux VSSO"
        const val RA_ANIMAL_SPECIALITES_SUR_LIEUX_GRIMP = "Spécialité sur les lieux GRIMP"
        const val RA_ANIMAL_SPECIALITES_SUR_LIEUX_SD = "Spécialité sur les lieux SD"
        const val RA_ANIMAL_SPECIALITES_SUR_LIEUX_NAUTIQUE = "Spécialité sur les lieux Nautique"
        const val RA_ANIMAL_SPECIALITES_SUR_LIEUX_GRED = "Spécialité sur les lieux GRED"


        const val RA_ACTION_APPROCHE = "Approche"
        const val RA_ACTION_IDENTIFICATION = "Identification"
        const val RA_ACTION_NEUTRALISATION = "Neutralisation"
        const val RA_ACTION_CAPTURE = "Capture"
        const val RA_ACTION_RELEVAGE = "Relevage"
        const val RA_ACTION_ASSISTANCE = "Assistance"
        const val RA_ACTION_CONDITIONNEMENT = "Conditionnement"
        const val RA_ACTION_TRANSPORT = "Transport"

        const val YEAR_2020 = "2020"
        const val YEAR_2021 = "2021"

    }
}